mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('feedback/', mainapp.feedback, name='feedback'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('search/', mainapp.search, name='search'),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path, path

app_name="ordersapp"

urlpatterns = [
   re_path(r'^$', ordersapp.orderList
           , name='orders_list'),
   path('create/', ordersapp.orderItemsCreate, name='order_create'),
   path('read/<int:pk>/', ordersapp.orderRead, name='order_read'),
   path('delete/<int:pk>/', ordersapp.orderDelete, name='order_delete'),
]

mysite/ordersapp/models.py
from django.db import models

from django.conf import settings
from mainapp.models import Product
from basketapp.models import Basket


class Order(models.Model):
    SENT_TO_PROCEED = 'STP'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=SENT_TO_PROCEED)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    # переопределяем метод, удаляющий объект
    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

mysite/ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

mysite/ordersapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse, redirect
from django.urls import reverse, reverse_lazy
from django.db import transaction

from django.forms import inlineformset_factory

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory

from django.conf import settings
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required


# class OrderList(ListView):
#     model = Order
#
#     def get_queryset(self):
#         return Order.objects.filter(user=self.request.user)
#
#     @method_decorator(login_required())
#     def dispatch(self, *args, **kwargs):
#         return super(ListView, self).dispatch(*args, **kwargs)
@login_required
def orderList(request):
    title = 'Заказы'
    orders = Order.objects.filter(user=request.user)
    basket = Basket.objects.filter(user=request.user)

    content = {
        'title': title,
        'orders': orders,
        'basket': basket,
    }

    return render(request, 'ordersapp/order_list.html', content)

@login_required
def orderItemsCreate(request):
    basket_items = Basket.objects.filter(user=request.user)
    if len(basket_items) > 0:
        productItemlist = []
        total_price_order = 0
        order_new = Order()
        order_new.user = request.user
        order_new.save()
        for num in basket_items:
            orderItems_new = OrderItem()
            orderItems_new.order = order_new
            orderItems_new.product = num.product
            orderItems_new.quantity = num.quantity
            orderItems_new.save()
            productItemlist.append(orderItems_new)
            total_price_order += num.product.price * num.quantity
        basket_items.delete()

        userItem = ShopUser.objects.get(pk=order_new.user.pk)

        content = {
            'order_new': order_new,
            'productItemlist': productItemlist,
            'userItem': userItem,
            'total_price_order': total_price_order
        }

        mailfrom = settings.EMAIL_HOST_USER
        mailto = [settings.EMAIL_HOST_USER]
        subject = 'Заказ № {0}'.format(order_new.id)
        message = 'Заказ № {0} Заказчик {1}. Телефон: {2}. Email: {3}'.format(order_new.id, userItem.first_name, userItem.phone, userItem.email)
        send_mail(subject, message, mailfrom, mailto)
        sent = True
        return render(request, 'ordersapp/order_info.html', content)
    else:
        return redirect('ordersapp:orders_list')


@login_required
def orderRead(request, pk):
    title = 'Просмотр заказа'

    basket = Basket.objects.filter(user=request.user)
    order = Order.objects.filter(user=request.user, pk=pk)
    orderItems = OrderItem.objects.filter(order__id=pk)
    userItem = ShopUser.objects.get(pk=request.user.pk)
    lengthDict = len(order)

    try:

        if userItem.pk == order[0].user.pk:

            content = {
                'title': title,
                'order': order,
                'basket': basket,
                'orderItems': orderItems
            }

            return render(request, 'ordersapp/order_detail.html', content)

    except IndexError:

            return redirect('ordersapp:orders_list')

# class OrderRead(DetailView):
#     model = Order
#
#     def get_queryset(self):
#         return Order.objects.filter(user=self.request.user)
#
#     def get_context_data(self, **kwargs):
#         context = super(OrderRead, self).get_context_data(**kwargs)
#         context['title'] = 'заказ/просмотр'
#         return context
#
#     @method_decorator(login_required())
#     def dispatch(self, *args, **kwargs):
#         return super(DetailView, self).dispatch(*args, **kwargs)


@login_required
def orderDelete(request, pk):
    title = 'Удалить заказа'

    basket = Basket.objects.filter(user=request.user)
    order = Order.objects.filter(user=request.user, pk=pk)
    orderItems = OrderItem.objects.filter(order__id=pk)
    userItem = ShopUser.objects.get(pk=request.user.pk)

    try:
        if userItem.pk == order[0].user.pk:
            if request.method == 'POST':
                order[0].delete()
                order[0].save()

                return redirect('ordersapp:orders_list')

    except IndexError:

        return redirect('ordersapp:orders_list')

    content = {'title': title,
               'userItem': userItem,
               'basket': basket,
               'order': order,
               'orderItems': orderItems
               }

    return render(request, 'ordersapp/order_confirm_delete.html', content)

# class OrderDelete(DeleteView):
#     model = Order
#     success_url = reverse_lazy('ordersapp:orders_list')
#
#     def get_queryset(self):
#         return Order.objects.filter(user=self.request.user)
#
#     @method_decorator(login_required())
#     def dispatch(self, *args, **kwargs):
#         return super(DeleteView, self).dispatch(*args, **kwargs)

mysite/ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <title>
        {% block title %}
           {{ title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% endblock %}

</head>
<body>
    <div class="container-super">
        <div class="top">
            <header class="header">
        <a href="{% url 'main' %}"><img src="{% static 'img/logo_demo2.jpg' %}" class="logo"></a>
        <div class="info-contact-position">
            <div class="search-position">
                <form class="form-inline" action="{% url 'search' %}" method="get">
                    <input type="search" placeholder="Введите ключевые слова" aria-label="Search" name="q" class="search-style">
                    <button type="submit" class="button-search" style="outline: none;">Поиск</button>
                </form>
            </div>
            <div style=" display: flex; justify-content: space-around;">
                <div>
                    <h4 style="font-size: 15px; margin-top: 12px;">Контакты:</h4>
                    <ul class="position-contact">
                        <li class="text-info-contact">Тел.: +7(927)-053-62-42</li>
                        <li class="text-info-contact">г. Маркс, ул. Бебеля,
                            д.&nbsp;58
                        </li>
                        <li class="text-info-contact">Email: frost2015s@yandex.ru</li>
                    </ul>
                </div>
                <div style="width: 152px;">
                    <h4 style="font-size: 15px; margin-top: 12px">Режим работы:</h4>
                    <ul class="position-contact">
                        <li class="text-info-contact">Пн.- Пт.: с 08:00 до 17:00</li>
                        <li class="text-info-contact">Сб.: с 08:00 до 14:00</li>
                        <li class="text-info-contact">Вс.: с 08:00 до 12:00</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="position-index-sign-in-and-menu">
            <div>{% include 'mainapp/includes/inc_menu.html' %}</div>

            <div class="position-index-sign-in">
                {% include 'mainapp/includes/inc_sing_in.html' %}
            </div>

        </div>
    </header>

    <div id="product">
    {% block content %}

    {% endblock %}
    </div>
    </div>
    {% block footer %}
        <footer class="footer">Copyright &copy;&nbsp;2018&nbsp;&mdash; {% now 'Y' %} Химик&nbsp;2.0 Все права защищены</footer>
    {% endblock %}
</div>

{% block js %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script defer src="{% static 'js/scrollingProducts.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script defer src="{% static 'js/inputFormPlusMinusInBasket.js' %}"></script>
{% endblock %}
</body>
</html>

mysite/ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}

{% block content %}
   <div class="category_delete">
       <div class="h2">Уверены, что хотите удалить?</div>
       {% include 'ordersapp/includes/inc_order_summary.html' %}
       <div style="display: flex;">
       <form action="{% url 'ordersapp:order_delete' order.0.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="Удалить" style="width: 100px; text-align: center; height: 40px; margin-right: 10px;">
       </form>
       <button class="btn btn-success button-delete-order" style="width: 100px; height: 40px;">
           <a href="{% url 'ordersapp:orders_list' %}" style="color: #ffffff; text-decoration: none;">Отмена</a>
       </button>
       </div>
   </div>
{% endblock %}

mysite/ordersapp/templates/ordersapp/order_detail.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block menu %}
    <div class="position-index-sign-in">
        {% include 'mainapp/includes/inc_sing_in.html' %}
    </div>
{% endblock %}

{% block content %}
    <div class="order-one-view">
        {% include 'ordersapp/includes/inc_order_detail_pdf.html' %}
    </div>
{% endblock %}

mysite/ordersapp/templates/ordersapp/order_form.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <title>
        {% block title %}
           {{ title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% endblock %}

</head>
<body>
    <h1>Онлайн-магазин</h1>
    <p>
      Номер заказа: <b>{{ order_new.id }}</b> <br>
      <span class="secondary">
        {{ order_new.created|date:"d.m.Y H:i:s" }}
      </span>
    </p>
    <h3>Покупатель</h3>
    <p>
      {{ userItem.first_name }}<br>
      {{ userItem.email }} <br>
      {{ userItem.phone }} <br>
    </p>
    <h3>Заказанные товары</h3>
    <table class="table">
      <thead>
        <tr>
          <th>Товар</th>
          <th>Стоймость</th>
          <th>Количество</th>
          <th>Всего</th>
        </tr>
      </thead>
      <tbody>
        {% for item in productItemlist %}
          <tr class="row{% cycle '1' '2' %}">
            <td>{{ item.product.name}}</td>
            <td>{{ item.product.price }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.get_product_cost }}</td>
          </tr>
        {% endfor %}
        <tr class="total">
          <td colspan="3">Всего:</td>
          <td>{{ total_price_order }}</td>
        </tr>
      </tbody>
    </table>
</body>
</html>

mysite/ordersapp/templates/ordersapp/order_info.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="login login-auth">
<div class="text-center head text-login">
    Заявка принята в обработку!
</div>
    <br>
    <h3>Спасибо за заказ!</h3>
    <h4>В ближайшее время с Вами свяжется менеджер.</h4>
    <p>Время получения заказа Вам сообщат по указанному телефону в личном кабинете. <br></p>
    <p>Если возникли вопросы обращайтесь по телефону: +7(927)-053-62-42<br></p>
  <br>
  <a href="{% url 'main' %}" style="text-decoration: none; margin-top: 5px; font-size: 22px">Вернуться на главную</a>
  <a href="{% url 'ordersapp:orders_list' %}" style="text-decoration: none; margin-top: 5px; margin-bottom: 30px; font-size: 22px">Ваши заказы</a>
</div>
{% endblock %}

mysite/ordersapp/templates/ordersapp/order_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu %}
    <div class="position-index-sign-in">
        {% include 'mainapp/includes/inc_sing_in.html' %}
    </div>
{% endblock %}

{% block content %}
<div class="order-list-view">
   <div class="h2" style="margin-top:20px; text-align:center; margin-bottom: 30px;">
       Ваши заказы, 
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list" style="text-align:center; border-bottom: 0; width: 900px;">
       <thead>
         <tr>
           <th style="border-bottom: 0;">ID</th>
           <th style="border-bottom: 0;">Создан</th>
           <th style="border-bottom: 0;">Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in orders %}
               {% if item.is_active %}
               <tr style="line-height:40px;">
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"d.m.Y H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:order_read' item.pk %}">
                           Просмотр заказа
                       </a>
                   </td>
                   <td>
                         <a href="{% url 'ordersapp:order_delete' item.pk %}">
                             <img src="{% static 'img/trash-empty.png' %}" alt="trash-empty" style="width: 33px"/>
                         </a>
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>
</div>
{% endblock %}