mysite/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('delete/<int:pk>/', authapp.delete, name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('feedback/', mainapp.feedback, name='feedback'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('search/', mainapp.search, name='search'),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(verbose_name='фотография', upload_to='users_avatars', blank='True', default='users_avatars/default.jpg')
    phone = models.CharField(verbose_name='номер телефона', max_length=30)

mysite/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    # параметры класса Meta (Дополнительные настройки для модели)
    # Метаданные модели - это «все, что не является полем»
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            # всем полям формы добавляется значение 'form-control'
            # http-атрибута 'class'. Это решает одну из самых больших
            # проблем при работе с формами в Django — их оформления при помощи css-стилей.
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'phone', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            # прячем поле с паролем HiddenInput()
            if field_name == 'password':
                field.widget = forms.HiddenInput()

mysite/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm
from django.contrib import auth
from django.urls import reverse
from authapp.models import ShopUser
from django.contrib.auth.decorators import login_required


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST or None)

    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main'))

    content = {'title': title,
               'login_form': login_form,
               'next': next,
               }

    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            username = request.POST['username']
            password = request.POST['password1']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main'))
    else:
        register_form = ShopUserRegisterForm()

    content = {
        'title': title,
        'register_form': register_form
    }

    return render(request, 'authapp/register.html', content)


@login_required
def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user) # instance=request.user - это экземпляр(правим конкретного пользователя)

    content = {'title': title, 'edit_form': edit_form}

    return render(request, 'authapp/edit.html', content)


@login_required
def delete(request, pk):
    title = 'Удаление'

    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        user.is_active = False
        user.save()

        return render(request, 'authapp/message_delete_user.html')

    content = {'title': title,
               'user_to_delete': user,
               }

    return render(request, 'authapp/delete.html', content)

mysite/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
    <div class="container conteiner-auth">
            {% block content %}

            {% endblock %}
    </div>
</body>
</html>

mysite/authapp/templates/authapp/delete.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="login login-auth">
<div class="text-center head text-login">
    Удаление учётной записи
</div>
    <div style="margin-top: 15px; font-size: 17px;">{{ user.first_name }}, Вы уверены? Что хотите удалить чётную запись {{ user.username }}
    ? </div>
    <form action="{% url 'auth:delete' user.pk %}"
          method="post" class="button-delete">
      {% csrf_token %}
      <input class="btn btn-danger" style="width: 150px; margin: 30px 0;" type="submit" value="Удалить">
      <a href="{% url 'auth:edit' %}" class="btn btn-success" style="width: 150px; margin: 30px 0;">
        Отмена
      </a>
    </form>
</div>
{% endblock %}

mysite/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="login login-auth" style="margin-top: 20px;">
<div class="text-center head text-login">
    Изменить данные
</div>
    <div class="user_avatar">
        <img src="/media/{{ user.avatar }}" onError="this.onerror=null;this.src='{% static 'img/default.jpg' %}';"
             class="user-avatars-404" style="width: 150px; margin: 10px; border-radius: 18px;"></div>
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <form action="{% url 'auth:delete' user.pk %}">
            {% csrf_token %}
            {{ user.as_p }}
            <input type="submit" value="Удалить учётную запись" style="margin-top: 7px;">
    </form>
    <a href="{% url 'main' %}" style="text-decoration: none; margin-top: 5px; margin-bottom: 30px;">На главную</a>
</div>
{% endblock %}

mysite/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="login login-auth">
<div class="text-center head text-login">
    Личный кабинет
</div>
    <form class="form-horizontal position-form-auth" action="{% url 'auth:login' %}" method="post" style="width: 300px;">
        {% csrf_token %}
            {% if next %}
                <input type="hidden" name="next" value="{{ next }}">
            {% endif %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>
    <a href="{% url 'auth:register' %}" style="text-decoration: none; margin-top: 10px;">Зарегистрироваться</a>
    <a href="{% url 'main' %}" style="text-decoration: none; margin-top: 5px; margin-bottom: 30px;">На главную</a>
</div>
{% endblock %}

mysite/authapp/templates/authapp/message_delete_user.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="login login-auth">
<div class="text-center head text-login">
    Удаление учётной записи
</div>
    <br>
    <h3>Учётная запись удалена успешно!</h3>
  <br>
  <a href="{% url 'main' %}" style="text-decoration: none; margin-top: 5px; margin-bottom: 30px; font-size: 22px">На главную</a>
</div>
{% endblock %}

mysite/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="login login-auth">
<div class="text-center head text-login">
    Регистрация
</div>
    <form class="form-horizontal registration-position" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
    <a href="{% url 'main' %}" style="text-decoration: none; margin-top: 5px;">На главную</a>
    <a href="{% url 'auth:login' %}" style="text-decoration: none; margin-top: 5px; margin-bottom: 30px;">Вернутся</a>
</div>
{% endblock %}

mysite/authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="login login-auth">
<div class="text-center head text-login">
    Регистрация прошла успешно!
</div>
    <br>
    <h3>Поздравляем! Вы зарегистрированы!</h3>
    <h4>Обязательно войдите в личный кабинет!</h4>
  <br>
  <a href="{% url 'main' %}" style="text-decoration: none; margin-top: 5px; margin-bottom: 30px; font-size: 22px">К покупкам!</a>
</div>
{% endblock %}