mysite/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/<int:quantity>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

mysite/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('feedback/', mainapp.feedback, name='feedback'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('search/', mainapp.search, name='search'),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path, path

app_name="ordersapp"

urlpatterns = [
   re_path(r'^$', ordersapp.orderList
           , name='orders_list'),
   path('create/', ordersapp.orderItemsCreate, name='order_create'),
   path('read/<int:pk>/', ordersapp.orderRead, name='order_read'),
   path('delete/<int:pk>/', ordersapp.orderDelete, name='order_delete'),
]

mysite/basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='время', auto_now_add=True)

    @property
    def product_cost(self):
        "return cost of all products this type"
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        "return total quantity for user"
        _items = Basket.objects.filter(user=self.user)
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    @property
    def total_cost(self):
        "return total cost for user"
        _items = Basket.objects.filter(user=self.user)
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost

    @property
    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_items(user):
        return Basket.objects.filter(user=user).order_by('product__category')

    @staticmethod
    def get_product(user, product):
        return Basket.objects.filter(user=user, product=product)

    @staticmethod
    def get_products_quantity(cls, user):
        basket_items = cls.get_items(user)
        basket_items_dic = {}
        [basket_items_dic.update({item.product: item.quantity}) for item in basket_items]

        return basket_items_dic

    @staticmethod
    def get_item(pk):
        return Basket.objects.filter(pk=pk).first()

mysite/basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product, ProductCategory
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.template.loader import render_to_string
from django.http import JsonResponse


@login_required
def basket(request):
    title = 'Корзина'
    basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

    content = {
        'title': title,
        'basket_items': basket_items,
        'basket': basket_items,
    }

    return render(request, 'basketapp/basket.html', content)


@login_required
def basket_add(request, pk, quantity, *args, **kwargs):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))

    try:
        if request.is_ajax():
            quantity = int(quantity)
            product = get_object_or_404(Product, pk=pk)
            old_basket_item = Basket.objects.filter(user=request.user, product=product)

            if old_basket_item:
                old_basket_item[0].quantity += quantity
                old_basket_item[0].save()
            else:
                new_basket_item = Basket(user=request.user, product=product)
                new_basket_item.quantity += quantity
                new_basket_item.save()

            products = Product.objects.filter(category__name='Новинки')
            basket = []
            basket = Basket.objects.filter(user=request.user)

            content = {
                'basket': basket,
            }

            result = render_to_string('mainapp/includes/inc_sing_in.html', content)
            return JsonResponse({'result': result})

    except ValueError:

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)

    if request.method == 'POST':
        basket_record.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, pk, quantity):
    try:
        if request.is_ajax():
            quantity = int(quantity)
            new_basket_item = Basket.objects.get(pk=int(pk))

            if quantity > 0:
                new_basket_item.quantity = quantity
                new_basket_item.save()
            else:
                new_basket_item.delete()

            basket = Basket.objects.filter(user=request.user).order_by('product__category')

            content = {
                'basket': basket,
            }

            result = render_to_string('basketapp/includes/inc_basket_list.html', content)

            return JsonResponse({'result': result})

    except ValueError:

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

mysite/basketapp/templates/basketapp/includes/inc_basket_list.html
{% load staticfiles %}

{% if basket|length > 0 %}
<div class="posiciton-basket-record-conteiner">
    {% for item in basket %}
    <div class="basket_record">
        <div>
            <a href="{% url 'products:product' item.product.pk %}">
                <img src="/media/{{ item.product.image }}" alt="{{ item.product.short_desc }}" style="width: 150px; margin-left: 15px; height: 150px;"></a>
        </div>
            <div style="margin-bottom: 15px; width: auto; justify-content: center;">
                <table style="width: 400px;">
                    <tr>
                        <td class="product_name"><b>{{ item.product.name }}</b></td>
                    </tr>
                    <tr>
                        <td class="product_name" style="height: 50px;">{{ item.product.short_desc }}</td>
                    </tr>
                    <tr>
                        <td style="display: flex; justify-content: space-around; align-items: baseline;">
                            <p class="price" style="width: auto;">{{ item.product.price }} &#8381 </p>
                            <p style="font-size: 22px; margin: 0;">&#215;</p>
                                    <div class="quantity-block">
                                        <button type="button" class="quantity-arrow-minus" style="outline: none;"> - </button>
                                        <input  type="number" class="quantity-num" name="{{ item.pk }}"  value="{{ item.quantity }}">
                                        <button type="button" class="quantity-arrow-plus" style="outline: none;"> + </button>
                                        <input type="button" value="Изменить" class="submit-input-basket" style="margin-top: 10px; width: 76px; height: 25px;">
                                    </div>
                            <p style="font-size: 22px; margin: 0;">&#61;</p>
                            <p class="price" style="width: auto;">{{ item.get_product_cost }} &#8381 </p>
                        </td>
                    </tr>
                </table>
            </div>
            <div style="display: flex; flex-direction: column;">
                <form action="{% url 'basket:remove' item.pk %}" method="post" style="text-align: center;">
                    {% csrf_token %}
                    {{ basket_record.as_p }}
                    <button type="submit" style="background-color: #ffffff; outline: none;"><img src="{% static 'img/trash-empty.png' %}" alt="trash-empty" style="width: 58px"/></button>
                </form>
            </div>
    </div>
    <hr class="line-basket-item" />
    {% endfor %}
</div>
<div class="basket-otders-block">
    <div><p class="text-basket-orders">Сумма заказа</p>
        <p class="price" style="font-size: 24px; justify-content: flex-start;">&#8381 {{ basket.0.total_cost }}</p>
    </div>
    <div class="button-basket-orders">
        <a href="{% url 'ordersapp:order_create' %}" style="text-decoration: none; color: #ffffff;">
            Заказать</a>
    </div>
</div>
{% else %}
<div style="width: 100%; display: flex; justify-content: center;"><img src="{% static 'img/cart-empty.png' %}"></div>
{% endif %}