mysite/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('delete/<int:pk>/', authapp.delete, name='delete'),
]

mysite/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/<int:quantity>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

mysite/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('feedback/', mainapp.feedback, name='feedback'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('search/', mainapp.search, name='search'),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path, path

app_name="ordersapp"

urlpatterns = [
   re_path(r'^$', ordersapp.orderList
           , name='orders_list'),
   path('create/', ordersapp.orderItemsCreate, name='order_create'),
   path('read/<int:pk>/', ordersapp.orderRead, name='order_read'),
   path('delete/<int:pk>/', ordersapp.orderDelete, name='order_delete'),
]

mysite/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return "{0} ({1})".format(self.name, self.category.name)

mysite/mainapp/forms.py
from django import forms


class ContactForm (forms.Form):
    name = forms.CharField(label='Имя', max_length=30)
    phone = forms.CharField(label='Номер телефона', max_length=30)
    email = forms.EmailField(label='Email', max_length=254)
    message = forms.CharField(label='', max_length=2000, widget=forms.Textarea, required=True)

mysite/mainapp/views.py
from django.shortcuts import render, get_object_or_404
import datetime
from .models import Product, ProductCategory
from basketapp.models import Basket
from random import random, sample
from django.db.models import Q
from django.views import View
from django.core.mail import send_mail
from django.conf import settings
from .forms import ContactForm

# В контроллер всегда передается как минимум один аргумент — объект запроса request.
# Мы пользуемся функцией render() из модуля django.shortcuts, которая должна
# получить как минимум два аргумента: объект request (по сути, он через нее пробрасывается в шаблон)
# и путь к шаблону. Внимание: контроллер всегда должен возвращать объект ответа — должен быть return.


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def main(request):
    title = 'Главная'
    links_menu = ProductCategory.objects.exclude(name='Новинки')
    products = Product.objects.filter(category__name='Новинки')

    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    content = {'title': title,
               'links_menu': links_menu,
               'products': products,
               'basket': basket,
               }
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None):
    links_menu = ProductCategory.objects.exclude(name='Новинки')
    basket = get_basket(request.user)

    category = get_object_or_404(ProductCategory, pk=pk)
    products = Product.objects.filter(category__pk=pk).order_by('price')
    title = '{0}'.format(category.name)
    
    content = {
        'title': title,
        'links_menu': links_menu,
        'category': category,
        'products': products,
        'basket': basket,
    }

    return render(request, 'mainapp/products_list.html', content)


def product(request, pk=None):
    product = get_object_or_404(Product, pk=pk)
    title = '{0}'.format(product.name)

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.exclude(name='Новинки'),
        'product': product,
        'same_products': Product.objects.filter(category__pk=product.category.pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)


def feedback(request):
    title = 'Написать нам'

    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    sent = False
    mailfrom = settings.EMAIL_HOST_USER
    mailto = [settings.EMAIL_HOST_USER]
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = 'Новое письмо от {}'.format(cd['name'])
            message = 'Прислал {}. Телефон: {}. Пишет: {}'.format(cd['email'], cd['phone'], cd['message'])
            send_mail(subject, message, mailfrom, mailto)
            sent = True
    else:
        form = ContactForm()

    content = {'title': title,
               'basket': basket,
               'form': form,
               'sent': sent
               }

    return render(request, 'mainapp/feedback.html', content)


def search(request, *args, **kwargs):

    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    query = request.GET.get('q').title()
    search_product = Product.objects.filter(
        Q(name__icontains=query)|
        Q(name__istartswith=query)|
        Q(short_desc__icontains=query)|
        Q(short_desc__istartswith=query)|
        Q(description__icontains=query)|
        Q(description__istartswith=query)
    )

    contextOne = {
        'search_product': search_product,
        'links_menu': ProductCategory.objects.exclude(name='Новинки'),
        'basket': basket,
    }

    contextTwo = {
        'links_menu': ProductCategory.objects.exclude(name='Новинки'),
        'basket': basket,
    }

    if query == '':
        return render(request, 'mainapp/search.html', contextTwo)
    else:
        return render(request, 'mainapp/search.html', contextOne)

mysite/mainapp/templates/mainapp/includes/inc_categories_menu.html
<nav class="category-wrap">
  <h3>Категории</h3>
    <ul class="">
    {% for link in links_menu %}
        <li>
            <a href="{% url 'products:category' link.pk %}"
                 class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                          active-links-menu
                        {% endif %}">
                {{ link.name }}
            </a>
        </li>
    {% endfor %}
</ul>
</nav>

mysite/mainapp/templates/mainapp/includes/inc_menu.html
<nav class="menu">
<ul class="topmenu position-menu">
    <li><a href="{% url 'main' %}"
           class="{% if request.resolver_match.url_name == 'main' %}active-menu{% endif %}">Главная</a>
    </li>
    <li><a href="{% url 'feedback' %}"
           class="{% if request.resolver_match.url_name == 'feedback' %}active-menu{% endif %}">Написать нам</a>
    </li>
    <li class="user-li">
        {% if user.is_authenticated %}
          <a href="{% url 'auth:logout' %}"
          class="{% if request.resolver_match.url_name == 'logout' %}active-menu{% endif %}">Выйти</a>
        {% else %}
          <a href="{% url 'auth:login' %}"
          class="{% if request.resolver_match.url_name == 'login' %}active-menu{% endif %}">
              <abbr title="Регистрация" style="text-decoration: none;">Войти</abbr></a>
        {% endif %}
    </li>
</ul>
</nav>

mysite/mainapp/templates/mainapp/includes/inc_sing_in.html
{% load staticfiles %}

{% if user.is_authenticated %}
<a href="{% url 'auth:edit' %}" class="edit-user-profil-login"><abbr title="Редактировать"
                                                                     style="text-decoration: none;">
    {{ user.first_name|default:'Пользователь' }}</abbr>
</a>
<a href="{% url 'ordersapp:orders_list' %}" class="order-style-view">
                       Ваши заказы
                   </a>
{% endif %}
<div class="sign-in-position">
        <img src="{% static 'img/basket-logo1.png' %}" class="basket-logo">
    {% if basket|length > 0 %}
        <a href="{% url 'basket:view' %}" class="mini-basket-position">
                    <span style="color: #da251c; font-weight: 600;">
                         &#8381 {{ basket.0.total_cost }}
                          ({{ basket.0.total_quantity }} шт.)
                    </span><br/></a>
    {% else %}
        <p class="if-basket-empty">Ваша корзина пуста</p>
    {% endif %}
</div>

mysite/mainapp/templates/mainapp/includes/inc_sing_in_two.html
{% load staticfiles %}

{% if user.is_authenticated %}
<a href="{% url 'auth:edit' %}" class="edit-user-profil-login"><abbr title="Редактировать"
                                                                     style="text-decoration: none;">
    {{ user.first_name|default:'Пользователь' }}</abbr>
</a>
<a href="{% url 'ordersapp:orders_list' %}" class="order-style-view">
    Ваши заказы
</a>
{% endif %}